---
apiVersion: v1
kind: Namespace
metadata:
  name: wisecow-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wisecow-namespace
  name: wisecow-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-wisecow
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-wisecow
    spec:
      containers:
      - image: manjunathkotabal/wisecow:latest
        imagePullPolicy: Always
        name: app-wisecow
        ports:
        - containerPort: 4499
---
apiVersion: v1
kind: Service
metadata:
  namespace: wisecow-namespace
  name: service-wisecow
spec:
  ports:
    - port: 80
      targetPort: 4499
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-wisecow
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: wisecow-namespace
  name: ingress-wisecow
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-wisecow
              port:
                number: 80