apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80  # Port on which your application is running inside the pod
      targetPort: 4499  # Port on which your application is listening inside the pod
      nodePort: 30000  # Specify a nodePort value within the range 30000-32767
